---
abstract: 'A Nephia plugin that provides data-validation feature'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-Data-Validator
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::Data::Validator:
    file: lib/Nephia/Plugin/Data/Validator.pm
    version: 0.02
requires:
  Data::Validator: 0
  Nephia: 0.07
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/Nephia-Plugin-Data-Validator/issues
  homepage: https://github.com/ytnobody/Nephia-Plugin-Data-Validator
  repository: git://github.com/ytnobody/Nephia-Plugin-Data-Validator.git
version: 0.02
